AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

# TODO: remove + fix code to pass everything
Metrics/BlockLength:
  Enabled: false

# TODO: remove + fix code to pass everything
Style/Documentation:
  Enabled: false


